import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const blogs = {
  "zh-hans": {
    "title": "游客的打卡手记",
    "items": [
      {
        "id": "xiaotao",
        "title": "在高加索，遇见一座“立体的历史课本”",
        "author": "@小桃",
        "excerpt": "作为一个偏爱小众秘境、又有点历史控的中国游客，走过那么多地方，格鲁吉亚依然能戳中我所有点：免签直接说走就走，比去欧洲申根国省了太多麻烦...",
        "content": [
          "出发去格鲁吉亚前，我已经走过了欧洲十几个国家、东南亚大半地区，习惯了巴黎埃菲尔铁塔的拥挤、罗马斗兽场的厚重，也沉迷过清迈的烟火、东京的精致，刷小红书时被Chronicle of Georgia——格鲁吉亚编年史纪念碑安利，起初只当是又一个“小众出片地”，直到真正站在那16根青铜巨柱下，才懂它为何能在我走过的众多古迹中，占据独一无二的位置。",
          "作为一个偏爱小众秘境、又有点历史控的中国游客，走过那么多地方，格鲁吉亚依然能戳中我所有点：免签直接说走就走，比去欧洲申根国省了太多麻烦，机票价格只有去法国、意大利的一半，物价更是低到惊喜——一杯当地红酒十几块，一顿地道美食几十块，比起欧美热门地的商业化，这里没有乌泱泱的旅行团，没有强行推销的小贩，能安安静静感受风景与历史的交融，这种松弛感，是我在伦敦、巴黎从未体会过的。",
          "爬上山顶看到纪念碑的那一刻，我居然有点恍惚。35米高的青铜巨柱直插天空，阳光洒在上面，浮雕的纹路都变得清晰起来——有诺亚方舟的传说，有中世纪国王加冕的场景，还有当地人酿酒、过节的画面，像一本摊开的立体历史书。我走过那么多历史古迹，埃及的金字塔厚重却遥远，希腊的神庙残缺却疏离，而这座纪念碑，既有历史的厚重，又有生活的温度。我忍不住对着浮雕一顿拍，一边拍一边查攻略，才知道格鲁吉亚是世界上最早种葡萄、酿红酒的地方，8000年的陶罐酿酒历史，和我们中国的农耕文明莫名有共鸣，比起法国波尔多的商业化酒庄，这里的酿酒文化更显纯粹，那一刻突然觉得，原来不同文明的根源，都是对生活的热爱，无关地域，无关语言。",
          "最惊喜的是，纪念碑旁边就是第比利斯海，远处能看到高加索雪山的轮廓，这种“人文+自然”的搭配，比我在瑞士看到的雪山湖泊多了一份历史底蕴，比我在国内看到的古迹多了一份辽阔。随手一拍都是氛围感大片，完全不用修图，我找了好几个机位，从全景拍到浮雕特写，甚至用无人机拍了整个山顶的景色，发朋友圈直接被问爆，大家都以为我去了什么冷门的欧洲秘境，没人想到，这个兼具东方烟火与西方浪漫的地方，是格鲁吉亚——一个被太多人忽略的欧亚交界宝地。",
          "打卡完纪念碑，我直接去了附近的酒庄，喝着当地的陶罐红酒，想起刚才在浮雕上看到的酿酒场景，突然就有了一种“穿越历史”的感觉。我喝过法国的波尔多、意大利的托斯卡纳，却唯独被格鲁吉亚的陶罐红酒打动，没有复杂的工艺，只有葡萄最本真的香气，就像这座纪念碑一样，不刻意、不张扬，却有着足够的吸引力。对我来说，这里不只是一个拍照打卡地，更是能让我静下心来，读懂高加索文明的地方，比起那些人挤人的热门景点，这种小众、有底蕴，还能收获满满的幸福感的地方，才是我跨国旅行的意义所在。"
        ]
      },
      {
        "id": "jack",
        "title": "徒步登顶，解锁一座“未完成的史诗”",
        "author": "@杰克",
        "excerpt": "作为一个常年背包旅行的美国人，我走过亚洲、欧洲、非洲的几十个国家，我总喜欢找那些不那么商业化、有故事的地方...",
        "content": [
          "作为一个常年背包旅行的美国人，我走过亚洲、欧洲、非洲的几十个国家，从东南亚的热闹市集，到非洲的原始草原，再到欧洲的古典古迹，我总喜欢找那些不那么商业化、有故事的地方，格鲁吉亚的Chronicle of Georgia，完全符合我对“完美打卡地”的期待——它没有过度宣传，没有拥挤的人群，没有商业化的纪念品商店，只有历史的厚重和自然的辽阔，这种纯粹感，是我在纽约、伦敦等大都市从未感受过的，也比我在欧洲其他热门古迹看到的景象，多了一份真实。",
          "我是从第比利斯老城出发，一路徒步登上山顶的，大概走了40分钟，沿途的风景越走越美，从城市的红屋顶，到远处的高加索山脉，再到波光粼粼的第比利斯海，每一步都有惊喜。我走过很多地方的徒步路线，尼泊尔的徒步路线险峻却偏僻，瑞士的徒步路线精致却商业化，而这条路线，既有自然的野趣，又有城市的烟火，沿途能看到当地居民在路边晾晒葡萄，能听到孩子们的笑声，能闻到空气中淡淡的红酒香气，这种生活化的徒步体验，让我觉得格外亲切。对我来说，徒步的过程本身就是一种旅行，比起坐车上山，我更愿意用脚步丈量这片土地，感受风里的气息，听听当地人的闲谈，读懂一座城市最真实的模样。",
          "当纪念碑出现在我眼前时，我被它的宏大震撼到了。16根青铜巨柱排列整齐，上面的浮雕密密麻麻，讲述着格鲁吉亚3000年的历史，从宗教传说到民俗风情，每一个细节都充满了力量。我见过美国的总统山，宏大却充满政治气息；见过埃及的方尖碑，古老却略显单调；而这座纪念碑，既有总统山的宏大，又有方尖碑的古老，更有着独属于欧亚交界的文化底蕴。后来我才知道，这座纪念碑因为苏联解体，资金断裂，并没有完全竣工，这种“未完成”的状态，反而让它更有魅力——它不像那些完美的纪念碑，更像是一段真实的历史，带着遗憾，却也带着希望，就像我走过的很多国家一样，不完美，却足够动人。",
          "我坐在巨柱旁边，晒着太阳，看着远处的风景，和一个当地的老人聊了起来。他告诉我，这座纪念碑是他们格鲁吉亚人的骄傲，每一根柱子都承载着他们的历史和信仰，就像自由女神像对于美国人的意义一样。我看着浮雕上的人物，想象着他们曾经的生活，突然觉得，历史从来都不是冰冷的文字，而是鲜活的故事，无论身处哪个国家，无论有着怎样的文化，人们对历史的敬畏、对生活的热爱，都是相通的。这种跨文化的共鸣，是我常年跨国旅行最大的收获。",
          "作为一个美国人，我习惯了欧美主流的历史和文化，从小在华盛顿纪念碑、林肯纪念堂的熏陶下长大，而格鲁吉亚这种欧亚交界的“边缘文明”，对我来说充满了吸引力。这里的东正教传统、独特的卡尔特维利语，还有苏联时期的痕迹，都让我觉得新鲜又神奇，和我在欧洲看到的基督教文化、在亚洲看到的东方文化，既有相似之处，又有截然不同的特色。打卡完纪念碑，我又去了黑海沿岸徒步，把历史和自然完美结合，这才是我想要的旅行——自由、真实，能收获不一样的体验，能读懂不同文化的魅力，这也是我一直坚持跨国旅行的原因。"
        ]
      },
      {
        "id": "lina",
        "title": "在高加索，遇见熟悉又陌生的文化回响",
        "author": "@莉娜",
        "excerpt": "我来自意大利，从小在教堂和历史古迹中长大。原本以为，再惊艳的纪念碑，也不会让我有太多惊喜，直到我来到格鲁吉亚...",
        "content": [
          "我来自意大利，从小在教堂和历史古迹中长大，罗马的斗兽场、佛罗伦萨的圣母百花大教堂、威尼斯的圣马可大教堂，早已刻进我的生活，原本以为，再惊艳的纪念碑，也不会让我有太多惊喜，毕竟我见过太多欧洲的古典瑰宝，直到我来到格鲁吉亚，看到了Chronicle of Georgia，这个坐落在高加索山脉脚下的纪念碑，彻底打破了我对“历史古迹”的固有认知。",
          "第一眼看到这座纪念碑，我就觉得很亲切——底层浮雕上的圣经故事，诺亚方舟、最后的晚餐，和我们意大利教堂里的壁画、雕塑几乎一样，那种东正教文化的同源感，让我瞬间就有了共鸣。我走过欧洲很多国家，法国的教堂精致华丽，德国的教堂庄严肃穆，而格鲁吉亚的这座纪念碑，把宗教文化与本土历史完美融合，既有欧洲宗教文化的影子，又有高加索地区的地域特色。我忍不住停下脚步，一点点解读浮雕上的细节，仿佛在看一段熟悉的历史，又带着一丝陌生的新鲜感，毕竟，这是基督教文明在高加索的延伸，和我们欧洲的宗教文化，既有相同之处，又有独特的韵味，这种跨地域的文化共鸣，是我在其他地方从未体会过的。",
          "对我来说，来格鲁吉亚打卡，还有一个重要的原因——性价比太高了。我走过欧洲很多国家，西欧的物价高得让人望而却步，一杯咖啡在巴黎要5欧元，一顿简餐在伦敦要20欧元，而在这里，一杯咖啡只要3欧元，一顿当地特色美食只要10欧元，而且风景一点也不输阿尔卑斯山，黑海沿岸的风光，甚至比地中海还要宁静美丽，没有拥挤的人群，没有商业化的喧嚣，只有纯粹的自然与美好。对我们欧洲人来说，这里就像是一个“低成本的度假天堂”，既能感受不一样的文化，又能享受轻松的假期，何乐而不为。",
          "我喜欢慢旅行，走过很多国家，我始终觉得，旅行的意义不在于打卡多少景点，而在于感受当地的生活。打卡完纪念碑，我没有着急离开，而是去了第比利斯老城。逛一逛硫磺浴池，那种温热的泉水，和我们意大利的温泉很像，却多了一丝独特的硫磺香气；淘一淘跳蚤市场，里面的手工艺品，既有欧洲的精致，又有东方的古朴；尝一尝当地的奶酪面包和红酒，奶酪的醇厚、红酒的甘甜，和我们意大利的美食有着异曲同工之妙，却又多了一份高加索的风味。我坐在老城的广场上，看着来往的人群，喝着当地的红酒，突然觉得，旅行的意义，就是在陌生的地方，找到熟悉的感动，就是跨越地域的界限，读懂不同文化的美好。",
          "纪念碑的雕塑风格也让我很感兴趣，设计师祖拉布·采列捷利，把拜占庭艺术、格鲁吉亚传统浮雕和现代主义完美融合，既有欧洲古典雕塑的精致，又有东方艺术的厚重。我忍不住拿出相机，拍下每一个细节，打算回去后和朋友分享，告诉他们，在高加索，有这样一座纪念碑，藏着欧洲文化的回响，也藏着不一样的东方魅力。我走过很多地方的雕塑，意大利的大卫雕塑精致绝伦，法国的维纳斯雕塑优雅动人，而这座纪念碑的雕塑，没有那么完美，却有着足够的力量，它承载着格鲁吉亚的历史，也承载着欧亚文化的交融，这就是它最独特的魅力。"
        ]
      },
      {
        "id": "katya",
        "title": "在纪念碑下，安放一份乡愁与安宁",
        "author": "@卡佳",
        "excerpt": "我来格鲁吉亚，与其说是旅行，不如说是寻找一份归属感。作为一个俄罗斯人，格鲁吉亚对我来说从来都不是一个陌生的国家...",
        "content": [
          "我来格鲁吉亚，与其说是旅行，不如说是寻找一份归属感。作为一个俄罗斯人，我走过很多国家，去过中国的北京、上海，感受过东方文化的魅力；去过欧洲的巴黎、柏林，体会过西方文化的浪漫；也去过东南亚的曼谷、吉隆坡，感受过热带风情的热闹，但格鲁吉亚对我来说，从来都不是一个陌生的国家，这里的文化、信仰，甚至是饮食，都和我们有着太多的相似之处，而Chronicle of Georgia，更是让我找到了久违的亲切感，这种亲切感，是我在其他任何国家都无法体会到的。",
          "从莫斯科飞到第比利斯，只要2个小时，机票便宜，而且免签，对我来说，就像一场短途的逃离。俄乌冲突之后，我一直觉得很疲惫，总想找一个安静的地方，放松自己，远离喧嚣和纷争，我去过很多国家，却都没有找到那种心安的感觉，直到来到格鲁吉亚。这里没有战争的阴影，没有喧嚣的人群，只有宁静和美好，就像我们俄罗斯的乡村一样，温暖而治愈，却又多了一份欧亚交界的独特风情。",
          "当我站在纪念碑前，看着那些熟悉的东正教圣像、苏联时期的艺术风格，眼眶突然有点湿润。这座纪念碑是苏联时期建造的，是我们共同的历史记忆，每一根青铜巨柱，都承载着我对过去的回忆，也承载着两个国家之间的情谊，就像莫斯科的红场、圣瓦西里大教堂一样，是我们心中不可替代的文化符号。我摸着浮雕上的纹路，仿佛能感受到当年建造者的心意，那种文化上的亲近感，是任何地方都无法替代的。我走过很多国家的历史古迹，中国的长城雄伟壮观，法国的埃菲尔铁塔浪漫迷人，却都没有这座纪念碑，能让我感受到如此强烈的归属感。",
          "我没有像其他游客那样，忙着拍照打卡，而是找了一个安静的角落，坐在草地上，看着远处的第比利斯海，吹着风，什么也不想。这里没有喧嚣，没有纷争，只有宁静和美好，让我暂时忘记了所有的烦恼。有时候，我会和当地的俄罗斯移民聊聊天，听他们讲述在这里的生活，那种同是异乡人的共鸣，让我觉得很温暖。我也会和当地的格鲁吉亚人交流，他们热情而善良，和我们俄罗斯人一样，有着对生活的热爱，有着对历史的敬畏，这种跨国家的情谊，让我格外感动。",
          "对我来说，这座纪念碑不仅仅是一个历史古迹，更是我心灵的寄托。它见证了格鲁吉亚的历史，也见证了我们两个国家的过往，在这里，我能找到文化的根，也能找到内心的安宁。每次来这里，我都会觉得很踏实，仿佛所有的乡愁，都能在这里安放。我走过很多地方，看过很多风景，却唯独偏爱这里，偏爱这份跨越地域的亲切感，偏爱这份宁静与美好。如果你来格鲁吉亚，一定要来看看这座纪念碑，它会让你读懂，什么是文化的共鸣，什么是心底的安宁，也会让你明白，无论身处何方，文化的力量，总能跨越地域的界限，温暖人心。"
        ]
      }
    ]
  },
  "zh-hant": {
    "title": "遊客的打卡手記",
    "items": [
      {
        "id": "xiaotao",
        "title": "在高加索，遇見一座「立體的歷史課本」",
        "author": "@小桃",
        "excerpt": "作為一個偏愛小眾秘境、又有點歷史控的中國遊客，走過那麼多地方，格魯吉亞依然能戳中我所有點：免簽直接說走就走，比去歐洲申根國省了太多麻煩...",
        "content": [
          "出發去格魯吉亞前，我已經走過了歐洲十幾個國家、東南亞大半地區，習慣了巴黎艾菲爾鐵塔的擁擠、羅馬競技場的厚重，也沉迷過清邁的煙火、東京的精緻，刷小紅書時被Chronicle of Georgia——格魯吉亞編年史紀念碑安利，起初只當是又一個「小眾出片地」，直到真正站在那16根青銅巨柱下，才懂它為何能在我走過的眾多古蹟中，佔據獨一無二的位置。",
          "作為一個偏愛小眾秘境、又有點歷史控的中國遊客，走過那麼多地方，格魯吉亞依然能戳中我所有點：免簽直接說走就走，比去歐洲申根國省了太多麻煩，機票價格只有去法國、義大利的一半，物價更是低到驚喜——一杯當地紅酒十幾塊，一頓地道美食幾十塊，比起歐美熱門地的商業化，這裡沒有烏泱泱的旅行團，沒有強行推銷的小販，能安安靜靜感受風景與歷史的交融，這種鬆弛感，是我在倫敦、巴黎從未體會過的。",
          "爬上山頂看到紀念碑的那一刻，我居然有點恍惚。35米高的青銅巨柱直插天空，陽光灑在上面，浮雕的紋路都變得清晰起來——有諾亞方舟的傳說，有中世紀國王加冕的場景，還有當地人釀酒、過節的畫面，像一本攤開的立體歷史書。我走過那麼多歷史古蹟，埃及的金字塔厚重卻遙遠，希臘的神廟殘缺卻疏離，而這座紀念碑，既有歷史的厚重，又有生活的溫度。我忍不住對著浮雕一頓拍，一邊拍一邊查攻略，才知道格魯吉亞是世界上最早種葡萄、釀紅酒的地方，8000年的陶罐釀酒歷史，和我們中國的農耕文明莫名有共鳴，比起法國波爾多的商業化酒莊，這裡的釀酒文化更顯純粹，那一刻突然覺得，原來不同文明的根源，都是對生活的熱愛，無關地域，無關語言。",
          "最驚喜的是，紀念碑旁邊就是第比利斯海，遠處能看到高加索雪山的輪廓，這種「人文+自然」的搭配，比我在瑞士看到的雪山湖泊多了一份歷史底蘊，比我在國內看到的古蹟多了一份遼闊。隨手一拍都是氛圍感大片，完全不用修圖，我找了好幾個機位，從全景拍到浮雕特寫，甚至用無人機拍了整個山頂的景色，發朋友圈直接被問爆，大家都以為我去了什麼冷門的歐洲秘境，沒人想到，這個兼具東方煙火與西方浪漫的地方，是格魯吉亞——一個被太多人忽略的歐亞交界寶地。",
          "打卡完紀念碑，我直接去了附近的酒莊，喝著當地的陶罐紅酒，想起剛才在浮雕上看到的釀酒場景，突然就有了一種「穿越歷史」的感覺。我喝過法國的波爾多、義大利的托斯卡納，卻唯獨被格魯吉亞的陶罐紅酒打動，沒有複雜的工藝，只有葡萄最本真的香氣，就像這座紀念碑一樣，不刻意、不張揚，卻有著足夠的吸引力。對我來說，這裡不只是一個拍照打卡地，更是能讓我靜下心來，讀懂高加索文明的地方，比起那些人擠人的熱門景點，這種小眾、有底蘊，還能收穫滿滿的幸福感的地方，才是我跨國旅行的意義所在。"
        ]
      },
      {
        "id": "jack",
        "title": "徒步登頂，解鎖一座「未完成的史詩」",
        "author": "@傑克",
        "excerpt": "作為一個常年背包旅行的美國人，我走過亞洲、歐洲、非洲的幾十個國家，我總喜歡找那些不那麼商業化、有故事的地方...",
        "content": [
          "作為一個常年背包旅行的美國人，我走過亞洲、歐洲、非洲的幾十個國家，從東南亞的熱鬧市集，到非洲的原始草原，再到歐洲的古典古蹟，我總喜歡找那些不那麼商業化、有故事的地方，格魯吉亞的Chronicle of Georgia，完全符合我對「完美打卡地」的期待——它沒有過度宣傳，沒有擁擠的人群，沒有商業化的紀念品商店，只有歷史的厚重和自然的遼闊，這種純粹感，是我在紐約、倫敦等大都市從未感受過的，也比我在歐洲其他熱門古蹟看到的景象，多了一份真實。",
          "我是從第比利斯老城出發，一路徒步登上山頂的，大概走了40分鐘，沿途的風景越走越美，從城市的紅屋頂，到遠處的高加索山脈，再到波光粼粼的第比利斯海，每一步都有驚喜。我走過很多地方的徒步路線，尼泊爾的徒步路線險峻卻偏僻，瑞士的徒步路線精緻卻商業化，而這條路線，既有自然的野趣，又有城市的煙火，沿途能看到當地居民在路邊晾曬葡萄，能聽到孩子們的笑聲，能聞到空氣中淡淡的紅酒香氣，這種生活化的徒步體驗，讓我覺得格外親切。對我來說，徒步的過程本身就是一種旅行，比起坐車上山，我更願意用腳步丈量這片土地，感受風裡的氣息，聽聽當地人的閒談，讀懂一座城市最真實的模樣。",
          "當紀念碑出現在我眼前時，我被它的宏大震撼到了。16根青銅巨柱排列整齊，上面的浮雕密密麻麻，講述著格魯吉亞3000年的歷史，從宗教傳說到民俗風情，每一個細節都充滿了力量。我見過美國的總統山，宏大卻充滿政治氣息；見過埃及的方尖碑，古老卻略顯單調；而這座紀念碑，既有總統山的宏大，又有方尖碑的古老，更有著獨屬於歐亞交界的文化底蘊。後來我才知道，這座紀念碑因為蘇聯解體，資金斷裂，並沒有完全竣工，這種「未完成」的狀態，反而讓它更有魅力——它不像那些完美的紀念碑，更像是一段真實的歷史，帶著遺憾，卻也帶著希望，就像我走過的很多國家一樣，不完美，卻足夠動人。",
          "我坐在巨柱旁邊，曬著太陽，看著遠處的風景，和一個當地的老人聊了起來。他告訴我，這座紀念碑是他們格魯吉亞人的驕傲，每一根柱子都承載著他們的歷史和信仰，就像自由女神像對於美國人的意義一樣。我看著浮雕上的人物，想像著他們曾經的生活，突然覺得，歷史從來都不是冰冷的文字，而是鮮活的故事，無論身處哪個國家，無論有著怎樣的文化，人們對歷史的敬畏、對生活的熱愛，都是相通的。這種跨文化的共鳴，是我常年跨國旅行最大的收穫。",
          "作為一個美國人，我習慣了歐美主流的歷史和文化，從小在華盛頓紀念碑、林肯紀念堂的薰陶下長大，而格魯吉亞這種歐亞交界的「邊緣文明」，對我來說充滿了吸引力。這裡的東正教傳統、獨特的卡爾特維利語，還有蘇聯時期的痕跡，都讓我覺得新鮮又神奇，和我在歐洲看到的基督教文化、在亞洲看到的東方文化，既有相似之處，又有截然不同的特色。打卡完紀念碑，我又去了黑海沿岸徒步，把歷史和自然完美結合，這才是我想要的旅行——自由、真實，能收穫不一樣的體驗，能讀懂不同文化的魅力，這也是我一直堅持跨國旅行的原因。"
        ]
      },
      {
        "id": "lina",
        "title": "在高加索，遇見熟悉又陌生的文化迴響",
        "author": "@莉娜",
        "excerpt": "我來自義大利，從小在教堂和歷史古蹟中長大。原本以為，再驚豔的紀念碑，也不會讓我有太多驚喜，直到我來到格魯吉亞...",
        "content": [
          "我來自義大利，從小在教堂和歷史古蹟中長大，羅馬的鬥獸場、佛羅倫斯的聖母百花大教堂、威尼斯的聖馬可大教堂，早已刻進我的生活，原本以為，再驚豔的紀念碑，也不會讓我有太多驚喜，畢竟我見過太多歐洲的古典瑰寶，直到我來到格魯吉亞，看到了Chronicle of Georgia，這個坐落在高加索山脈腳下的紀念碑，徹底打破了我對「歷史古蹟」的固有認知。",
          "第一眼看到這座紀念碑，我就覺得很親切——底層浮雕上的聖經故事，諾亞方舟、最後的晚餐，和我們義大利教堂裡的壁畫、雕塑幾乎一樣，那種東正教文化的同源感，讓我瞬間就有了共鳴。我走過歐洲很多國家，法國的教堂精緻華麗，德國的教堂莊嚴肅穆，而格魯吉亞的這座紀念碑，把宗教文化與本土歷史完美融合，既有歐洲宗教文化的影子，又有高加索地區的地域特色。我忍不住停下腳步，一點點解讀浮雕上的細節，彷彿在看一段熟悉的歷史，又帶著一絲陌生的新鮮感，畢竟，這是基督教文明在高加索的延伸，和我們歐洲的宗教文化，既有相同之處，又有獨特的韻味，這種跨地域的文化共鳴，是我在其他地方從未體會過的。",
          "對我來說，來格魯吉亞打卡，還有一個重要的原因——性價比太高了。我走過歐洲很多國家，西歐的物價高得讓人望而卻步，一杯咖啡在巴黎要5歐元，一頓簡餐在倫敦要20歐元，而在這裡，一杯咖啡只要3歐元，一頓當地特色美食只要10歐元，而且風景一點也不輸阿爾卑斯山，黑海沿岸的風光，甚至比地中海還要寧靜美麗，沒有擁擠的人群，沒有商業化的喧囂，只有純粹的自然與美好。對我們歐洲人來說，這裡就像是一個「低成本的度假天堂」，既能感受不一樣的文化，又能享受輕鬆的假期，何樂而不為。",
          "我喜歡慢旅行，走過很多國家，我始終覺得，旅行的意義不在於打卡多少景點，而在於感受當地的生活。打卡完紀念碑，我沒有著急離開，而是去了第比利斯老城。逛一逛硫磺浴池，那種溫熱的泉水，和我們義大利的溫泉很像，卻多了一絲獨特的硫磺香氣；淘一淘跳蚤市場，裡面的手工藝品，既有歐洲的精緻，又有東方的古樸；嘗一嘗當地的奶酪麵包和紅酒，奶酪的醇厚、紅酒的甘甜，和我們義大利的美食有著異曲同工之妙，卻又多了一份高加索的風味。我坐在老城的廣場上，看著來往的人群，喝著當地的紅酒，突然覺得，旅行的意義，就是在陌生的地方，找到熟悉的感動，就是跨越地域的界限，讀懂不同文化的美好。",
          "紀念碑的雕塑風格也讓我很感興趣，設計師祖拉布·采列捷利，把拜占庭藝術、格魯吉亞傳統浮雕和現代主義完美融合，既有歐洲古典雕塑的精緻，又有東方藝術的厚重。我忍不住拿出相機，拍下每一個細節，打算回去後和朋友分享，告訴他們，在高加索，有這樣一座紀念碑，藏著歐洲文化的迴響，也藏著不一樣的東方魅力。我走過很多地方的雕塑，義大利的大衛雕塑精緻絕倫，法國的維納斯雕塑優雅動人，而這座紀念碑的雕塑，沒有那麼完美，卻有著足夠的力量，它承載著格魯吉亞的歷史，也承載著歐亞文化的交融，這就是它最獨特的魅力。"
        ]
      },
      {
        "id": "katya",
        "title": "在紀念碑下，安放一份鄉愁與安寧",
        "author": "@卡佳",
        "excerpt": "我來格魯吉亞，與其說是旅行，不如說是尋找一份歸屬感。作為一個俄羅斯人，格魯吉亞對我來說從來都不是一個陌生的國家...",
        "content": [
          "我來格魯吉亞，與其說是旅行，不如說是尋找一份歸屬感。作為一個俄羅斯人，我走過很多國家，去過中國的北京、上海，感受過東方文化的魅力；去過歐洲的巴黎、柏林，體會過西方文化的浪漫；也去過東南亞的曼谷、吉隆坡，感受過熱帶風情的熱鬧，但格魯吉亞對我來說，從來都不是一個陌生的國家，這裡的文化、信仰，甚至是飲食，都和我們有著太多的相似之處，而Chronicle of Georgia，更是讓我找到了久違的親切感，這種親切感，是我在其他任何國家都無法體會到的。",
          "從莫斯科飛到第比利斯，只要2個小時，機票便宜，而且免簽，對我來說，就像一場短途的逃離。俄烏衝突之後，我一直覺得很疲憊，總想找一個安靜的地方，放鬆自己，遠離喧囂和紛爭，我去過很多國家，卻都沒有找到那種心安的感覺，直到來到格魯吉亞。這裡沒有戰爭的陰影，沒有喧囂的人群，只有寧靜和美好，就像我們俄羅斯的鄉村一樣，溫暖而治癒，卻又多了一份歐亞交界的獨特風情。",
          "當我站在紀念碑前，看著那些熟悉的東正教聖像、蘇聯時期的藝術風格，眼眶突然有點濕潤。這座紀念碑是蘇聯時期建造的，是我們共同的歷史記憶，每一根青銅巨柱，都承載著我對過去的回憶，也承載著兩個國家之間的情誼，就像莫斯科的紅場、聖瓦西里大教堂一樣，是我們心中不可替代的文化符號。我摸著浮雕上的紋路，彷彿能感受到當年建造者的心意，那種文化上的親近感，是任何地方都無法替代的。我走過很多國家的歷史古蹟，中國的長城雄偉壯觀，法國的艾菲爾鐵塔浪漫迷人，卻都沒有這座紀念碑，能讓我感受到如此強烈的歸屬感。",
          "我沒有像其他遊客那樣，忙著拍照打卡，而是找了一個安靜的角落，坐在草地上，看著遠處的第比利斯海，吹著風，什麼也不想。這裡沒有喧囂，沒有紛爭，只有寧靜和美好，讓我暫時忘記了所有的煩惱。有時候，我會和當地的俄羅斯移民聊聊天，聽他們講述在這裡的生活，那種同是異鄉人的共鳴，讓我覺得很溫暖。我也會和當地的格魯吉亞人交流，他們熱情而善良，和我們俄羅斯人一樣，有著對生活的熱愛，有著對歷史的敬畏，這種跨國家的情誼，讓我格外感動。",
          "對我來說，這座紀念碑不僅僅是一個歷史古蹟，更是我心靈的寄託。它見證了格魯吉亞的歷史，也見證了我們兩個國家的過往，在這裡，我能找到文化的根，也能找到內心的安寧。每次來這裡，我都會覺得很踏實，彷彿所有的鄉愁，都能在這裡安放。我走過很多地方，看過很多風景，卻唯獨偏愛這裡，偏愛這份跨越地域的親切感，偏愛這份寧靜與美好。如果你來格魯吉亞，一定要來看看這座紀念碑，它會讓你讀懂，什麼是文化的共鳴，什麼是心底的安寧，也會讓你明白，無論身處何方，文化的力量，總能跨越地域的界限，溫暖人心。"
        ]
      }
    ]
  },
  "en": {
    "title": "Tourist Check-in Notes",
    "items": [
      {
        "id": "xiaotao",
        "title": "Encountering a '3D History Book' in the Caucasus",
        "author": "@Xiaotao",
        "excerpt": "As a Chinese tourist who prefers niche hidden gems and loves history, Georgia hits all the right spots for me: visa-free travel makes it incredibly easy...",
        "content": [
          "Before heading to Georgia, I had already traveled to over a dozen European countries and most of Southeast Asia. I was used to the crowds at the Eiffel Tower, the weight of the Colosseum, the vibrant street life of Chiang Mai, and the refinement of Tokyo. When I saw the Chronicles of Georgia recommended online, I initially thought it was just another 'niche photo spot'. But it wasn't until I stood beneath those 16 massive bronze pillars that I understood why it holds such a unique place among all the historical sites I've visited.",
          "As a Chinese tourist who loves history and niche destinations, Georgia checks all the boxes: the visa-free policy makes spontaneous trips easy, saving the hassle of Schengen visas. Flights are half the price of going to France or Italy, and the cost of living is surprisingly low—a glass of local wine costs just a couple of dollars, and an authentic meal is extremely affordable. Unlike the over-commercialized popular spots in Europe, there are no massive tour groups here, no pushy vendors. You can quietly experience the blend of scenery and history. This sense of relaxation is something I never felt in London or Paris.",
          "The moment I climbed to the top of the hill and saw the monument, I was slightly dazed. The 35-meter-tall bronze pillars pierce the sky, and as the sunlight hits them, the intricate relief patterns become crystal clear—there are legends of Noah's Ark, scenes of medieval kings' coronations, and depictions of locals making wine and celebrating festivals. It looks like an open, 3D history book. I've visited many historical monuments: the pyramids in Egypt are monumental but distant, the Greek temples are beautiful but fragmented. However, this monument possesses both the weight of history and the warmth of life. I couldn't stop taking pictures of the reliefs, and while looking up information, I learned that Georgia is the birthplace of winemaking, with an 8,000-year history of Qvevri wine. This resonates inexplicably with China's agricultural civilization. Compared to the commercial wineries in Bordeaux, the wine culture here feels much purer. At that moment, I realized that the roots of different civilizations are all based on a love for life, regardless of geography or language.",
          "The biggest surprise was that right next to the monument is the Tbilisi Sea, and in the distance, you can see the outline of the snowy Caucasus Mountains. This combination of 'humanities + nature' carries more historical depth than the snowy mountains and lakes I saw in Switzerland, and it feels more expansive than the historical sites in my home country. Any casual photo turns out to be a cinematic masterpiece without needing any editing. I found several great angles, from panoramic shots to close-ups of the reliefs, and even used a drone to capture the entire hilltop. When I posted the photos on social media, my friends kept asking me where I was, assuming it was some hidden gem in Europe. No one expected this place, blending Eastern warmth and Western romance, to be Georgia—a treasure at the crossroads of Europe and Asia that too many people overlook.",
          "After visiting the monument, I went straight to a nearby winery. Drinking the local Qvevri wine and recalling the winemaking scenes I had just seen on the reliefs, I suddenly felt like I was 'traveling through history'. I've tasted wines from Bordeaux and Tuscany, but I was uniquely moved by Georgia's Qvevri wine. There are no overly complex processes, just the purest aroma of the grapes. Just like this monument: unpretentious, not overly publicized, yet possessing an undeniable attraction. For me, this isn't just a place to take photos; it's a place where I can calm down and understand Caucasian civilization. Compared to those crowded, popular attractions, this niche, culturally rich place that brings a deep sense of happiness is exactly what gives meaning to my cross-border travels."
        ]
      },
      {
        "id": "jack",
        "title": "Hiking to the Top: Unlocking an 'Unfinished Epic'",
        "author": "@Jack",
        "excerpt": "As an American who frequently backpacks around the world, I've traveled to dozens of countries across Asia, Europe, and Africa. I always look for places that are less commercialized and full of stories...",
        "content": [
          "As an American who frequently backpacks around the world, I've traveled to dozens of countries across Asia, Europe, and Africa. From the bustling markets of Southeast Asia to the wild savannas of Africa and the classical monuments of Europe, I always seek out places that are less commercialized and rich in stories. The Chronicles of Georgia perfectly met my expectations of a 'perfect travel destination'—it lacks excessive promotion, massive crowds, and commercial souvenir shops. There is only the weight of history and the vastness of nature. This sense of purity is something I've never felt in megacities like New York or London, and it feels more authentic than the scenes at other popular European historical sites.",
          "I started my journey from the Old Town of Tbilisi and hiked all the way to the top of the hill, which took about 40 minutes. The scenery along the way became increasingly beautiful—from the red roofs of the city to the distant Caucasus Mountains and the sparkling Tbilisi Sea; every step held a surprise. I've hiked in many places: the trails in Nepal are rugged but remote, the trails in Switzerland are exquisite but commercialized. However, this route combines the wildness of nature with the lively atmosphere of the city. Along the way, I saw locals drying grapes by the road, heard children laughing, and smelled the faint aroma of wine in the air. This slice-of-life hiking experience made me feel incredibly welcome. For me, the process of hiking is a journey in itself. Rather than taking a car up the mountain, I prefer to measure the land with my footsteps, feel the breeze, listen to the locals chat, and truly understand the authentic face of a city.",
          "When the monument finally appeared before me, I was stunned by its sheer scale. The 16 bronze pillars are neatly arranged, covered in dense reliefs that tell the 3,000-year history of Georgia. From religious legends to folk customs, every detail is full of power. I've seen Mount Rushmore in the US, which is grand but highly political; I've seen the obelisks in Egypt, which are ancient but somewhat monotonous. This monument, however, possesses the grandeur of Mount Rushmore, the antiquity of the obelisks, and a cultural depth unique to the crossroads of Europe and Asia. Later, I learned that due to the collapse of the Soviet Union and a lack of funding, the monument was never completely finished. This 'unfinished' state actually gives it more charm. Unlike those flawless monuments, it feels more like a piece of real history—carrying regrets but also hope. Just like many of the countries I've visited: imperfect, yet deeply moving.",
          "I sat beside the massive pillars, soaking in the sun and looking at the distant scenery, and started chatting with a local elderly man. He told me that this monument is the pride of the Georgian people. Every pillar carries their history and faith, much like what the Statue of Liberty means to Americans. Looking at the figures on the reliefs and imagining their past lives, I suddenly realized that history is never just cold text; it's a collection of living stories. Regardless of the country or culture, people's reverence for history and love for life are universal. This cross-cultural resonance is the greatest reward of my years of global travel.",
          "As an American, I grew up accustomed to mainstream European and American history and culture, surrounded by the Washington Monument and the Lincoln Memorial. Therefore, Georgia's 'fringe civilization' at the intersection of Europe and Asia is incredibly fascinating to me. The Orthodox traditions, the unique Kartvelian language, and the traces of the Soviet era all feel fresh and magical. It shares similarities with the Christian culture I've seen in Europe and the Eastern culture I've seen in Asia, yet it has its completely distinct characteristics. After visiting the monument, I went hiking along the Black Sea coast, perfectly blending history and nature. This is exactly the kind of travel I want—free, authentic, offering different experiences, and allowing me to appreciate the charm of different cultures. This is why I continue to travel the world."
        ]
      },
      {
        "id": "lina",
        "title": "Finding Familiar yet Strange Cultural Echoes in the Caucasus",
        "author": "@Lina",
        "excerpt": "I come from Italy, growing up surrounded by churches and historical monuments. I thought no monument could surprise me anymore, until I came to Georgia...",
        "content": [
          "I come from Italy, growing up surrounded by churches and historical monuments. The Colosseum in Rome, the Florence Cathedral, and St. Mark's Basilica in Venice are deeply ingrained in my life. I initially thought that no matter how stunning a monument might be, it wouldn't surprise me much, given that I've seen so many of Europe's classical treasures. That was until I came to Georgia and saw the Chronicles of Georgia. This monument, sitting at the foothills of the Caucasus Mountains, completely shattered my preconceived notions of 'historical sites'.",
          "The first time I saw this monument, I felt a strong sense of familiarity. The biblical stories on the bottom reliefs—Noah's Ark, the Last Supper—look almost identical to the frescoes and sculptures in our Italian churches. That sense of shared origin in Orthodox and Catholic cultures instantly resonated with me. I've traveled across many European countries: French churches are exquisitely ornate, German churches are solemn and majestic. But this Georgian monument perfectly blends religious culture with local history. It carries the shadow of European religious culture while showcasing the regional characteristics of the Caucasus. I couldn't help but stop and decipher the details on the reliefs one by one, as if looking at a familiar history mixed with a touch of strange novelty. After all, this is the extension of Christian civilization into the Caucasus, sharing similarities with our European religious culture but possessing its own unique charm. This cross-regional cultural resonance is something I've never experienced anywhere else.",
          "For me, there is another important reason to visit Georgia—the incredible value for money. I've traveled extensively in Europe, and the high cost of living in Western Europe can be daunting. A cup of coffee in Paris costs 5 euros, and a simple meal in London is 20 euros. Here, a coffee is only 3 euros, and a local specialty meal is just 10 euros. Moreover, the scenery easily rivals the Alps. The views along the Black Sea coast are even more tranquil and beautiful than the Mediterranean. There are no massive crowds, no commercial noise—only pure nature and beauty. For us Europeans, this is like a 'low-cost holiday paradise' where you can experience a different culture while enjoying a relaxing vacation. Why wouldn't you come?",
          "I prefer slow travel. Having visited many countries, I always feel that the meaning of travel isn't about ticking off as many attractions as possible, but about experiencing local life. After visiting the monument, I didn't rush to leave. Instead, I went to the Old Town of Tbilisi. I visited the sulfur baths; the warm spring water is very similar to our thermal baths in Italy, but with a unique hint of sulfur. I browsed the flea market, where the handicrafts feature both European refinement and Eastern rustic charm. I tasted the local cheese bread and wine; the richness of the cheese and the sweetness of the wine share similarities with Italian cuisine but carry a distinct Caucasian flavor. Sitting in the Old Town square, watching people pass by and sipping local wine, I suddenly felt that the true meaning of travel is finding familiar touches in strange places, crossing geographical boundaries, and understanding the beauty of different cultures.",
          "The sculptural style of the monument also intrigued me greatly. The designer, Zurab Tsereteli, perfectly blended Byzantine art, traditional Georgian reliefs, and modernism. It has the refinement of classical European sculpture and the weight of Eastern art. I couldn't resist taking out my camera to capture every detail, planning to share them with my friends back home. I want to tell them that in the Caucasus, there is a monument that holds the echoes of European culture as well as a unique Eastern charm. I've seen sculptures all over the world: Michelangelo's David in Italy is exquisitely perfect, the Venus de Milo in France is elegantly moving. The sculptures on this monument may not be 'perfect' in the classical sense, but they possess immense power. They carry the history of Georgia and the blending of Eurasian cultures. That is its most unique charm."
        ]
      },
      {
        "id": "katya",
        "title": "Finding Nostalgia and Peace Beneath the Monument",
        "author": "@Katya",
        "excerpt": "Coming to Georgia, for me, is less about traveling and more about finding a sense of belonging. As a Russian, Georgia has never been a strange country to me...",
        "content": [
          "Coming to Georgia, for me, is less about traveling and more about finding a sense of belonging. As a Russian, I have traveled to many countries: I've been to Beijing and Shanghai in China, experiencing the charm of Eastern culture; I've been to Paris and Berlin in Europe, feeling the romance of Western culture; and I've visited Bangkok and Kuala Lumpur in Southeast Asia, enjoying the lively tropical vibe. However, Georgia has never been a strange country to me. The culture, faith, and even the food here share so many similarities with ours. The Chronicles of Georgia, in particular, helped me find a long-lost sense of familiarity—a feeling I couldn't find in any other country.",
          "Flying from Moscow to Tbilisi takes only 2 hours. The flights are cheap, and it's visa-free. For me, it feels like a short escape. Following the recent conflicts, I've felt constantly exhausted, always wanting to find a quiet place to relax and get away from the noise and disputes. I've visited many countries, but none gave me that sense of peace until I came to Georgia. There is no shadow of war here, no noisy crowds—only tranquility and beauty. It feels just like the Russian countryside, warm and healing, but with the unique flair of the Eurasian crossroads.",
          "When I stood in front of the monument, looking at the familiar Orthodox icons and the Soviet-era architectural style, my eyes suddenly welled up with tears. This monument was built during the Soviet era; it is our shared historical memory. Every massive bronze pillar carries my memories of the past and the friendship between our two nations. Much like the Red Square or St. Basil's Cathedral in Moscow, it is an irreplaceable cultural symbol in our hearts. Touching the textures of the reliefs, I felt as if I could sense the intentions of the builders from back then. That cultural closeness is irreplaceable. I've visited historical sites in many countries—the Great Wall of China is majestic, the Eiffel Tower in France is romantic—but none of them gave me such a strong sense of belonging as this monument.",
          "Unlike other tourists, I didn't rush to take photos. Instead, I found a quiet corner, sat on the grass, looked at the distant Tbilisi Sea, felt the breeze, and just emptied my mind. There is no noise here, no conflict, only peace and beauty, allowing me to temporarily forget all my worries. Sometimes, I chat with local Russian immigrants and listen to their stories about living here. That resonance of being fellow expats makes me feel very warm. I also interact with the local Georgians; they are passionate and kind. Just like us Russians, they have a deep love for life and a reverence for history. This transnational friendship deeply moves me.",
          "For me, this monument is not just a historical site; it is a spiritual refuge. It has witnessed the history of Georgia and the shared past of our two countries. Here, I can find my cultural roots and inner peace. Every time I visit, I feel grounded, as if all my nostalgia can safely rest here. I've traveled to many places and seen many landscapes, but I uniquely favor this place. I favor this cross-regional familiarity and this peace and beauty. If you ever come to Georgia, you must visit this monument. It will help you understand what cultural resonance is, what inner peace is, and it will make you realize that no matter where you are, the power of culture can always cross geographical boundaries and warm people's hearts."
        ]
      }
    ]
  },
  "ru": {
    "title": "Заметки туристов",
    "items": [
      {
        "id": "xiaotao",
        "title": "Встреча с «трехмерным учебником истории» на Кавказе",
        "author": "@Сяотао",
        "excerpt": "Как китайский турист, предпочитающий скрытые жемчужины и любящий историю, Грузия попадает в самое сердце: безвизовый режим делает спонтанные поездки невероятно легкими...",
        "content": [
          "Перед поездкой в Грузию я уже побывала в более чем дюжине европейских стран и большей части Юго-Восточной Азии. Я привыкла к толпам у Эйфелевой башни, тяжести Колизея, суете Чиангмая и утонченности Токио. Когда я увидела рекомендации Хроник Грузии в интернете, я сначала подумала, что это просто очередная «нишевая локация для фото». Но только оказавшись под этими 16 массивными бронзовыми колоннами, я поняла, почему это место занимает такое уникальное положение среди всех исторических памятников, которые я посетила.",
          "Как китайский турист, любящий историю и нетуристические места, Грузия идеально мне подходит: безвизовый режим позволяет легко сорваться в поездку, избавляя от хлопот с шенгенскими визами. Авиабилеты стоят в два раза дешевле, чем во Францию или Италию, а цены просто удивительно низкие — бокал местного вина стоит копейки, а настоящая местная еда очень доступна. В отличие от переполненных туристами популярных мест в Европе, здесь нет огромных туристических групп, нет навязчивых торговцев. Вы можете спокойно наслаждаться слиянием пейзажей и истории. Этого чувства расслабленности я никогда не испытывала в Лондоне или Париже.",
          "В тот момент, когда я поднялась на вершину холма и увидела памятник, я была немного ошеломлена. 35-метровые бронзовые колонны пронзают небо, и когда на них падают солнечные лучи, замысловатые узоры барельефов становятся кристально четкими — здесь есть легенды о Ноевом ковчеге, сцены коронации средневековых королей, а также изображения местных жителей, делающих вино и отмечающих праздники. Это похоже на открытую трехмерную книгу истории. Я посетила множество исторических памятников: египетские пирамиды монументальны, но далеки, греческие храмы прекрасны, но разрушены. Однако этот памятник обладает как тяжестью истории, так и теплом жизни. Я не могла перестать фотографировать барельефы, и, читая информацию о них, я узнала, что Грузия — родина виноделия, с 8000-летней историей вина в квеври. Это необъяснимо перекликается с земледельческой цивилизацией Китая. По сравнению с коммерческими винодельнями в Бордо, винная культура здесь кажется гораздо чище. В тот момент я поняла, что корни разных цивилизаций основаны на любви к жизни, независимо от географии или языка.",
          "Самым большим сюрпризом стало то, что прямо рядом с памятником находится Тбилисское море, а вдали виднеются очертания заснеженных Кавказских гор. Это сочетание «гуманитарных наук и природы» несет в себе большую историческую глубину, чем заснеженные горы и озера, которые я видела в Швейцарии, и кажется более просторным, чем исторические места в моей родной стране. Любое случайное фото получается кинематографичным шедевром без всякой обработки. Я нашла несколько отличных ракурсов, от панорамных снимков до крупных планов барельефов, и даже использовала дрон, чтобы запечатлеть весь холм. Когда я опубликовала фотографии в социальных сетях, мои друзья постоянно спрашивали, где я, предполагая, что это какая-то скрытая жемчужина в Европе. Никто не ожидал, что это место, сочетающее восточное тепло и западную романтику, — Грузия, сокровище на перекрестке Европы и Азии, которое слишком многие упускают из виду.",
          "После посещения памятника я отправилась прямо на близлежащую винодельню. Выпив местного вина из квеври и вспомнив сцены виноделия, которые я только что видела на барельефах, я вдруг почувствовала, что «путешествую сквозь историю». Я пробовала вина из Бордо и Тосканы, но грузинское вино из квеври тронуло меня по-особенному. Здесь нет слишком сложных процессов, только чистейший аромат винограда. Точно так же, как и этот памятник: непритязательный, не слишком разрекламированный, но обладающий неоспоримой притягательностью. Для меня это не просто место для фотографий; это место, где я могу успокоиться и понять кавказскую цивилизацию. По сравнению с этими переполненными, популярными достопримечательностями, это нишевое, культурно богатое место, которое приносит глубокое чувство счастья, — это именно то, что придает смысл моим международным путешествиям."
        ]
      },
      {
        "id": "jack",
        "title": "Восхождение на вершину: Открывая «Незавершенный эпос»",
        "author": "@Джек",
        "excerpt": "Как американец, который часто путешествует по миру с рюкзаком, я побывал в десятках стран Азии, Европы и Африки. Я всегда ищу места, которые менее коммерциализированы и полны историй...",
        "content": [
          "Как американец, который часто путешествует по миру с рюкзаком, я побывал в десятках стран Азии, Европы и Африки. От шумных рынков Юго-Восточной Азии до диких саванн Африки и классических памятников Европы, я всегда ищу места, которые менее коммерциализированы и полны историй. Хроники Грузии идеально оправдали мои ожидания от «идеального туристического направления» — здесь нет чрезмерной рекламы, огромных толп и коммерческих сувенирных магазинов. Есть только тяжесть истории и просторы природы. Это чувство чистоты — то, чего я никогда не испытывал в таких мегаполисах, как Нью-Йорк или Лондон, и оно кажется более подлинным, чем сцены в других популярных исторических местах Европы.",
          "Я начал свой путь из Старого города Тбилиси и прошел пешком до самой вершины холма, что заняло около 40 минут. Пейзажи по пути становились все красивее — от красных крыш города до далеких Кавказских гор и сверкающего Тбилисского моря; каждый шаг таил в себе сюрприз. Я ходил в походы во многих местах: тропы в Непале суровы, но отдалены, тропы в Швейцарии изысканны, но коммерциализированы. Однако этот маршрут сочетает в себе дикость природы с живой атмосферой города. По пути я видел местных жителей, сушащих виноград у дороги, слышал смех детей и чувствовал слабый аромат вина в воздухе. Этот поход, полный повседневной жизни, заставил меня почувствовать себя невероятно желанным гостем. Для меня процесс похода — это уже путешествие само по себе. Вместо того, чтобы ехать в гору на машине, я предпочитаю измерять землю своими шагами, чувствовать ветерок, слушать разговоры местных жителей и по-настоящему понимать подлинное лицо города.",
          "Когда памятник наконец предстал передо мной, я был ошеломлен его огромными масштабами. 16 бронзовых колонн аккуратно выстроены в ряд, покрыты плотными барельефами, рассказывающими о 3000-летней истории Грузии. От религиозных легенд до народных обычаев, каждая деталь полна силы. Я видел гору Рашмор в США, которая грандиозна, но в высшей степени политизирована; я видел обелиски в Египте, которые древние, но несколько однообразные. Этот памятник, однако, обладает величием горы Рашмор, древностью обелисков и культурной глубиной, уникальной для перекрестка Европы и Азии. Позже я узнал, что из-за распада Советского Союза и нехватки финансирования памятник так и не был полностью завершен. Это «незавершенное» состояние на самом деле придает ему больше очарования. В отличие от тех безупречных памятников, он больше похож на кусок реальной истории — несущий сожаления, но также и надежду. Как и многие страны, в которых я побывал: несовершенные, но глубоко трогательные.",
          "Я сидел рядом с массивными колоннами, греясь на солнце и глядя на далекие пейзажи, и начал болтать с местным пожилым мужчиной. Он сказал мне, что этот памятник — гордость грузинского народа. Каждая колонна несет в себе их историю и веру, подобно тому, что Статуя Свободы значит для американцев. Глядя на фигуры на барельефах и представляя их прошлые жизни, я вдруг понял, что история — это никогда не просто холодный текст; это собрание живых историй. Независимо от страны или культуры, почтение людей к истории и любовь к жизни универсальны. Этот кросс-культурный резонанс — величайшая награда за мои годы путешествий по миру.",
          "Как американец, я вырос, привыкнув к господствующей европейской и американской истории и культуре, в окружении монумента Вашингтона и мемориала Линкольна. Поэтому грузинская «окраинная цивилизация» на стыке Европы и Азии невероятно увлекательна для меня. Православные традиции, уникальный картвельский язык и следы советской эпохи — все это кажется свежим и волшебным. Она имеет сходство с христианской культурой, которую я видел в Европе, и восточной культурой, которую я видел в Азии, но при этом обладает своими совершенно отличными характеристиками. После посещения памятника я отправился в поход вдоль побережья Черного моря, идеально сочетая историю и природу. Это именно тот вид путешествий, который я хочу — свободный, подлинный, предлагающий разные впечатления и позволяющий мне оценить очарование разных культур. Вот почему я продолжаю путешествовать по миру."
        ]
      },
      {
        "id": "lina",
        "title": "Находя знакомые, но странные культурные отголоски на Кавказе",
        "author": "@Лина",
        "excerpt": "Я из Италии, выросла в окружении церквей и исторических памятников. Я думала, что ни один памятник больше не сможет меня удивить, пока я не приехала в Грузию...",
        "content": [
          "Я из Италии, выросла в окружении церквей и исторических памятников. Колизей в Риме, Флорентийский собор и базилика Святого Марка в Венеции глубоко укоренились в моей жизни. Изначально я думала, что независимо от того, насколько потрясающим может быть памятник, он меня не сильно удивит, учитывая, что я видела так много классических сокровищ Европы. Так было до тех пор, пока я не приехала в Грузию и не увидела Хроники Грузии. Этот памятник, расположенный в предгорьях Кавказских гор, полностью разрушил мои предвзятые представления об «исторических местах».",
          "Когда я впервые увидела этот памятник, я почувствовала сильное чувство знакомства. Библейские сюжеты на нижних барельефах — Ноев ковчег, Тайная вечеря — выглядят почти идентично фрескам и скульптурам в наших итальянских церквях. Это чувство общего происхождения в православной и католической культурах мгновенно нашло во мне отклик. Я путешествовала по многим европейским странам: французские церкви изысканно богато украшены, немецкие церкви торжественны и величественны. Но этот грузинский памятник идеально сочетает религиозную культуру с местной историей. Он несет в себе тень европейской религиозной культуры, демонстрируя при этом региональные особенности Кавказа. Я не могла не остановиться и не расшифровать детали на барельефах один за другим, как будто глядя на знакомую историю, смешанную с оттенком странной новизны. В конце концов, это распространение христианской цивилизации на Кавказ, имеющее сходство с нашей европейской религиозной культурой, но обладающее собственным уникальным очарованием. Этот межрегиональный культурный резонанс — это то, чего я никогда нигде больше не испытывала.",
          "Для меня есть еще одна важная причина посетить Грузию — невероятное соотношение цены и качества. Я много путешествовала по Европе, и высокая стоимость жизни в Западной Европе может пугать. Чашка кофе в Париже стоит 5 евро, а простой обед в Лондоне — 20 евро. Здесь кофе стоит всего 3 евро, а местное фирменное блюдо — всего 10 евро. Более того, пейзажи легко соперничают с Альпами. Виды вдоль побережья Черного моря даже более спокойные и красивые, чем Средиземноморье. Здесь нет огромных толп, нет коммерческого шума — только чистая природа и красота. Для нас, европейцев, это как «бюджетный рай для отдыха», где можно познакомиться с другой культурой, наслаждаясь расслабляющим отпуском. Почему бы вам не приехать?",
          "Я предпочитаю медленные путешествия. Побывав во многих странах, я всегда чувствую, что смысл путешествия заключается не в том, чтобы отметить как можно больше достопримечательностей, а в том, чтобы окунуться в местную жизнь. После посещения памятника я не спешила уезжать. Вместо этого я отправилась в Старый город Тбилиси. Я посетила серные бани; теплая родниковая вода очень похожа на наши термальные ванны в Италии, но с уникальным оттенком серы. Я побродила по блошиному рынку, где изделия ручной работы сочетают в себе европейскую изысканность и восточное деревенское очарование. Я попробовала местный сырный хлеб и вино; богатство сыра и сладость вина имеют сходство с итальянской кухней, но несут в себе отчетливый кавказский колорит. Сидя на площади Старого города, наблюдая за проходящими мимо людьми и потягивая местное вино, я вдруг почувствовала, что истинный смысл путешествий заключается в том, чтобы находить знакомые штрихи в незнакомых местах, пересекать географические границы и понимать красоту разных культур.",
          "Скульптурный стиль памятника также меня очень заинтриговал. Дизайнер Зураб Церетели идеально смешал византийское искусство, традиционные грузинские барельефы и модернизм. В нем есть утонченность классической европейской скульптуры и вес восточного искусства. Я не могла удержаться, чтобы не достать камеру и не запечатлеть каждую деталь, планируя поделиться ими с друзьями дома. Я хочу сказать им, что на Кавказе есть памятник, который хранит в себе отголоски европейской культуры, а также уникальное восточное очарование. Я видела скульптуры по всему миру: Давид Микеланджело в Италии изысканно совершенен, Венера Милосская во Франции элегантно трогательна. Скульптуры на этом памятнике могут быть не «идеальными» в классическом смысле, но они обладают огромной силой. Они несут в себе историю Грузии и смешение евразийских культур. В этом его самое уникальное очарование."
        ]
      },
      {
        "id": "katya",
        "title": "Находя ностальгию и покой под памятником",
        "author": "@Катя",
        "excerpt": "Приезд в Грузию для меня — это не столько путешествие, сколько поиск чувства принадлежности. Как для русской, Грузия никогда не была для меня чужой страной...",
        "content": [
          "Приезд в Грузию для меня — это не столько путешествие, сколько поиск чувства принадлежности. Как русская, я побывала во многих странах: я была в Пекине и Шанхае в Китае, ощутив очарование восточной культуры; я была в Париже и Берлине в Европе, почувствовав романтику западной культуры; и я посетила Бангкок и Куала-Лумпур в Юго-Восточной Азии, наслаждаясь живой тропической атмосферой. Однако Грузия никогда не была для меня чужой страной. Культура, вера и даже еда здесь имеют так много общего с нашими. Хроники Грузии, в частности, помогли мне обрести давно утраченное чувство знакомства — чувство, которое я не могла найти ни в одной другой стране.",
          "Перелет из Москвы в Тбилиси занимает всего 2 часа. Авиабилеты дешевые, и виза не нужна. Для меня это похоже на короткий побег. После недавних конфликтов я постоянно чувствовала усталость, всегда хотела найти тихое место, чтобы расслабиться и уйти от шума и споров. Я побывала во многих странах, но ни одна из них не дала мне такого чувства покоя, пока я не приехала в Грузию. Здесь нет тени войны, нет шумных толп — только спокойствие и красота. Это похоже на русскую сельскую местность, теплую и исцеляющую, но с уникальным колоритом евразийского перекрестка.",
          "Когда я стояла перед памятником, глядя на знакомые православные иконы и архитектурный стиль советской эпохи, мои глаза вдруг наполнились слезами. Этот памятник был построен в советское время; это наша общая историческая память. Каждая массивная бронзовая колонна хранит мои воспоминания о прошлом и дружбе между нашими двумя народами. Как и Красная площадь или храм Василия Блаженного в Москве, это незаменимый культурный символ в наших сердцах. Прикасаясь к фактурам барельеф��в, я чувствовала, как будто могу ощутить намерения строителей того времени. Эта культурная близость незаменима. Я посетила исторические места во многих странах — Великая Китайская стена величественна, Эйфелева башня во Франции романтична, — но ни одно из них не дало мне такого сильного чувства принадлежности, как этот памятник.",
          "В отличие от других туристов, я не спешила фотографироваться. Вместо этого я нашла тихий уголок, села на траву, посмотрела на далекое Тбилисское море, почувствовала ветерок и просто освободила свой разум. Здесь нет шума, нет конфликтов, только мир и красота, что позволяет мне временно забыть обо всех своих заботах. Иногда я болтаю с местными русскими иммигрантами и слушаю их истории о жизни здесь. Этот резонанс того, что мы земляки-экспаты, заставляет меня чувствовать себя очень тепло. Я также общаюсь с местными грузинами; они страстные и добрые. Как и мы, русские, они глубоко любят жизнь и почитают историю. Эта транснациональная дружба глубоко трогает меня.",
          "Для меня этот памятник — не просто историческое место; это духовное убежище. Он был свидетелем истории Грузии и общего прошлого наших двух стран. Здесь я могу найти свои культурные корни и внутренний покой. Каждый раз, когда я приезжаю сюда, я чувствую себя заземленной, как будто вся моя ностальгия может безопасно покоиться здесь. Я путешествовала по многим местам и видела множество пейзажей, но я по-особенному люблю это место. Мне нравится эта межрегиональная близость, этот мир и красота. Если вы когда-нибудь приедете в Грузию, вы должны посетить этот памятник. Он поможет вам понять, что такое культурный резонанс, что такое внутренний покой, и заставит вас осознать, что независимо от того, где вы находитесь, сила культуры всегда может пересечь географические границы и согреть сердца людей."
        ]
      }
    ]
  },
  "ka": {
    "title": "ტურისტების შთაბეჭდილებები",
    "items": [
      {
        "id": "xiaotao",
        "title": "კავკასიაში 'სამგანზომილებიანი ისტორიის წიგნის' აღმოჩენა",
        "author": "@სიაოტაო",
        "excerpt": "როგორც ჩინელი ტურისტი, რომელსაც ურჩევნია უცნობი ადგილები და უყვარს ისტორია, საქართველო იდეალური აღმოჩნდა: უვიზო რეჟიმი მოგზაურობას ამარტივებს...",
        "content": [
          "საქართველოში გამგზავრებამდე უკვე ვესტუმრე ევროპის ათზე მეტ ქვეყანას და სამხრეთ-აღმოსავლეთ აზიის დიდ ნაწილს. მიჩვეული ვიყავი ეიფელის კოშკთან ხალხმრავლობას, კოლიზეუმის სიდიადეს, ჩიანგ მაის ქუჩის ცხოვრებას და ტოკიოს დახვეწილობას. როდესაც ონლაინ ვნახე საქართველოს მატიანეს რეკომენდაცია, თავიდან ვიფიქრე, რომ ეს იყო კიდევ ერთი 'ნიშური ადგილი ფოტოებისთვის'. მაგრამ მხოლოდ მას შემდეგ, რაც დავდექი იმ 16 მასიური ბრინჯაოს სვეტის ქვეშ, მივხვდი, რატომ უკავია მას ასეთი უნიკალური ადგილი ჩემს მიერ მონახულებულ ყველა ისტორიულ ადგილს შორის.",
          "როგორც ჩინელი ტურისტი, რომელსაც უყვარს ისტორია და ნაკლებად ცნობილი მიმართულებები, საქართველო იდეალურია: უვიზო პოლიტიკა აადვილებს სპონტანურ მოგზაურობებს და თავიდან გარიდებთ შენგენის ვიზებთან დაკავშირებულ პრობლემებს. ფრენები საფრანგეთში ან იტალიაში წასვლაზე ორჯერ იაფია, და ცხოვრების ღირებულება საოცრად დაბალია — ერთი ჭიქა ადგილობრივი ღვინო მხოლოდ რამდენიმე დოლარი ღირს, და ნამდვილი ადგილობრივი კერძი ძალიან ხელმისაწვდომია. ევროპის ზედმეტად კომერციალიზებული პოპულარული ადგილებისგან განსხვავებით, აქ არ არის მასიური ტურისტული ჯგუფები, არ არიან მომაბეზრებელი გამყიდველები. თქვენ შეგიძლიათ მშვიდად დატკბეთ პეიზაჟებისა და ისტორიის შერწყმით. მოდუნების ეს შეგრძნება ისეთია, რაც არასდროს განმიცდია ლონდონში ან პარიზში.",
          "იმ მომენტში, როდესაც ავედი ბორცვის წვერზე და დავინახე მონუმენტი, ცოტათი გაოგნებული დავრჩი. 35 მეტრის სიმაღლის ბრინჯაოს სვეტები ცას სწვდება, და როდესაც მზის სინათლე ეცემა მათ, რთული რელიეფური ნიმუშები კრისტალურად ნათელი ხდება — აქ არის ნოეს კიდობნის ლეგენდები, შუა საუკუნეების მეფეების კორონაციის სცენები, და ადგილობრივების მიერ ღვინის დაყენებისა და ფესტივალების აღნიშვნის სცენები. ის ჰგავს ღია, სამგანზომილებიან ისტორიის წიგნს. მე ბევრი ისტორიული მონუმენტი მომინახულებია: პირამიდები ეგვიპტეში მონუმენტურია, მაგრამ შორეული, ბერძნული ტაძრები ლამაზია, მაგრამ ფრაგმენტული. თუმცა, ეს მონუმენტი ფლობს როგორც ისტორიის სიმძიმეს, ასევე ცხოვრების სითბოს. ვერ ვწყვეტდი რელიეფების ფოტოების გადაღებას, და ინფორმაციის მოძიებისას გავიგე, რომ საქართველო მეღვინეობის სამშობლოა, 8,000-წლიანი ქვევრის ღვინის ისტორიით. ეს აუხსნელად ეხმიანება ჩინეთის სასოფლო-სამეურნეო ცივილიზაციას. ბორდოს კომერციულ ღვინის ქარხნებთან შედარებით, ღვინის კულტურა აქ ბევრად უფრო სუფთად იგრძნობა. იმ მომენტში მივხვდი, რომ სხვადასხვა ცივილიზაციების ფესვები ყველა ეფუძნება ცხოვრების სიყვარულს, მიუხედავად გეოგრაფიისა ან ენისა.",
          "ყველაზე დიდი სიურპრიზი ის იყო, რომ მონუმენტის გვერდით არის თბილისის ზღვა, და შორს შეგიძლიათ დაინახოთ თოვლიანი კავკასიონის მთების კონტურები. 'ჰუმანიტარული მეცნიერებების + ბუნების' ეს კომბინაცია უფრო დიდ ისტორიულ სიღრმეს ატარებს, ვიდრე შვეიცარიაში ნანახი თოვლიანი მთები და ტბები, და უფრო ვრცლად იგრძნობა, ვიდრე ისტორიული ადგილები ჩემს სამშობლოში. ნებისმიერი შემთხვევითი ფოტო კინემატოგრაფიულ შედევრად იქცევა ყოველგვარი დამუშავების გარეშე. მე ვიპოვე რამდენიმე შესანიშნავი რაკურსი, პანორამული კადრებიდან რელიეფების ახლო ხედებამდე, და დრონიც კი გამოვიყენე მთელი ბორცვის დასაფიქსირებლად. როდესაც ფოტოები სოციალურ ქსელებში გამოვაქვეყნე, ჩემი მეგობრები გამუდმებით მეკითხებოდნენ სად ვიყავი, ეგონათ რომ ეს ევროპის რაიმე ფარული მარგალიტი იყო. არავინ ელოდა, რომ ეს ადგილი, რომელიც აერთიანებს აღმოსავლურ სითბოს და დასავლურ რომანტიკას, იქნებოდა საქართველო — საგანძური ევროპისა და აზიის გზაჯვარედინზე, რომელსაც ძალიან ბევრი ადამიანი უგულებელყოფს.",
          "მონუმენტის მონახულების შემდეგ, პირდაპირ მიმდებარე ღვინის ქარხანაში წავედი. ადგილობრივი ქვევრის ღვინის სმისას და რელიეფებზე ახლახან ნანახი მეღვინეობის სცენების გახსენებისას, უცებ ვიგრძენი, რომ 'ისტორიაში ვმოგზაურობდი'. მე გამისინჯავს ღვინოები ბორდოდან და ტოსკანადან, მაგრამ უნიკალურად აღმაფრთოვანა საქართველოს ქვევრის ღვინომ. არ არის ზედმეტად რთული პროცესები, მხოლოდ ყურძნის ყველაზე სუფთა არომატი. ისევე როგორც ეს მონუმენტი: უპრეტენზიო, არც თუ ისე ფართოდ რეკლამირებული, მაგრამ ფლობს უდავო მიმზიდველობას. ჩემთვის ეს არ არის მხოლოდ ფოტოების გადასაღები ადგილი; ეს არის ადგილი, სადაც შემიძლია დავმშვიდდე და გავიგო კავკასიური ცივილიზაცია. იმ ხალხმრავალ, პოპულარულ ატრაქციონებთან შედარებით, ეს ნიშური, კულტურულად მდიდარი ადგილი, რომელსაც მოაქვს ბედნიერების ღრმა გრძნობა, არის ზუსტად ის, რაც აზრს აძლევს ჩემს ტრანსსასაზღვრო მოგზაურობებს."
        ]
      },
      {
        "id": "jack",
        "title": "მთის წვერზე ასვლა: 'დაუსრულებელი ეპოსის' აღმოჩენა",
        "author": "@ჯეკი",
        "excerpt": "როგორც ამერიკელი, რომელიც ხშირად მოგზაურობს ზურგჩანთით მთელ მსოფლიოში, ვყოფილვარ აზიის, ევროპისა და აფრიკის ათობით ქვეყანაში. მე ყოველთვის ვეძებ ადგილებს, რომლებიც ნაკლებად კომერციალიზებულია და სავსეა ისტორიებით...",
        "content": [
          "როგორც ამერიკელი, რომელიც ხშირად მოგზაურობს ზურგჩანთით მთელ მსოფლიოში, ვყოფილვარ აზიის, ევროპისა და აფრიკის ათობით ქვეყანაში. სამხრეთ-აღმოსავლეთ აზიის ხმაურიანი ბაზრებიდან აფრიკის ველურ სავანებამდე და ევროპის კლასიკურ მონუმენტებამდე, მე ყოველთვის ვეძებ ადგილებს, რომლებიც ნაკლებად კომერციალიზებულია და მდიდარია ისტორიებით. საქართველოს მატიანემ სრულად გაამართლა ჩემი მოლოდინები 'იდეალური სამოგზაურო მიმართულების' შესახებ — მას აკლია გადაჭარბებული რეკლამა, მასიური ხალხმრავლობა და კომერციული სუვენირების მაღაზიები. აქ მხოლოდ ისტორიის სიმძიმე და ბუნების უკიდეგანობაა. სისუფთავის ეს შეგრძნება ისეთია, რაც არასდროს განმიცდია მეგაპოლისებში, როგორიცაა ნიუ-იორკი ან ლონდონი, და ის უფრო ავთენტურად იგრძნობა, ვიდრე სცენები სხვა პოპულარულ ევროპულ ისტორიულ ადგილებში.",
          "ჩემი მოგზაურობა დავიწყე თბილისის ძველი ქალაქიდან და ავედი მთის წვერამდე, რასაც დაახლოებით 40 წუთი დასჭირდა. პეიზაჟი გზად სულ უფრო და უფრო ლამაზდებოდა — ქალაქის წითელი სახურავებიდან შორეულ კავკასიონის მთებამდე და ცქრიალა თბილისის ზღვამდე; ყოველი ნაბიჯი მალავდა სიურპრიზს. მე ბევრგან მივლია ფეხით: ბილიკები ნეპალში უხეშია, მაგრამ მიუვალ ადგილებში, ბილიკები შვეიცარიაში დახვეწილია, მაგრამ კომერციალიზებული. თუმცა, ეს მარშრუტი აერთიანებს ბუნების ველურობას ქალაქის ცოცხალ ატმოსფეროსთან. გზად დავინახე ადგილობრივები, რომლებიც გზის პირას ყურძენს აშრობდნენ, გავიგონე ბავშვების სიცილი და ვიგრძენი ღვინის სუსტი სურნელი ჰაერში. ამ ყოველდღიური ცხოვრებით სავსე ლაშქრობის გამოცდილებამ წარმოუდგენლად სასურველ სტუმრად მაგრძნობინა თავი. ჩემთვის, ლაშქრობის პროცესი თავისთავად მოგზაურობაა. მთაზე მანქანით ასვლას მირჩევნია მიწა ჩემი ნაბიჯებით გავზომო, ვიგრძნო ნიავი, მოვუსმინო ადგილობრივების საუბარს და ნამდვილად გავიგო ქალაქის ავთენტური სახე.",
          "როდესაც მონუმენტი საბოლოოდ გამოჩნდა ჩემს წინ, გაოგნებული დავრჩი მისი მასშტაბით. 16 ბრინჯაოს სვეტი აკურატულადაა განლაგებული, დაფარული მკვრივი რელიეფებით, რომლებიც მოგვითხრობენ საქართველოს 3,000-წლიან ისტორიას. რელიგიური ლეგენდებიდან დაწყებული ხალხური ადათ-წესებით დამთავრებული, ყოველი დეტალი სავსეა ძალით. მე მინახავს რაშმორის მთა აშშ-ში, რომელიც გრანდიოზულია, მაგრამ ძალზე პოლიტიზებული; მინახავს ობელისკები ეგვიპტეში, რომლებიც უძველესია, მაგრამ გარკვეულწილად ერთფეროვანი. ეს მონუმენტი კი ფლობს რაშმორის მთის სიდიადეს, ობელისკების სიძველეს და კულტურულ სიღრმეს, რომელიც უნიკალურია ევროპისა და აზიის გზაჯვარედინისთვის. მოგვიანებით გავიგე, რომ საბჭოთა კავშირის დაშლისა და დაფინანსების ნაკლებობის გამო, მონუმენტი არასოდეს დასრულებულა ბოლომდე. ეს 'დაუსრულებელი' მდგომარეობა სინამდვილეში მას მეტ ხიბლს ანიჭებს. იმ უნაკლო მონუმენტებისგან განსხვავებით, ის უფრო რეალური ისტორიის ნაწილად იგრძნობა — რომელიც ატარებს სინანულს, მაგრამ ასევე იმედს. ისევე როგორც ბევრი ქვეყანა, სადაც ვყოფილვარ: არასრულყოფილი, მაგრამ ღრმად ამაღელვებელი.",
          "ვიჯექი მასიური სვეტების გვერდით, ვეფიცხებოდი მზეს და ვუყურებდი შორეულ პეიზაჟს, და დავიწყე საუბარი ადგილობრივ ხანდაზმულ მამაკაცთან. მან მითხრა, რომ ეს მონუმენტი ქართველი ხალხის სიამაყეა. ყოველი სვეტი ატარებს მათ ისტორიას და რწმენას, ისევე როგორც თავისუფლების ქანდაკება ნიშნავს ამერიკელებისთვის. ვუყურებდი რელიეფებზე გამოსახულ ფიგურებს და წარმოვიდგენდი მათ წარსულ ცხოვრებას, უცებ მივხვდი, რომ ისტორია არასოდეს არის მხოლოდ ცივი ტექსტი; ეს არის ცოცხალი ისტორიების კრებული. მიუხედავად ქვეყნისა თუ კულტურისა, ხალხის პატივისცემა ისტორიისადმი და ცხოვრების სიყვარული უნივერსალურია. ეს კროს-კულტურული რეზონანსი არის ჩემი მრავალწლიანი გლობალური მოგზაურობის უდიდესი ჯილდო.",
          "როგორც ამერიკელი, გავიზარდე მიჩვეული მეინსტრიმულ ევროპულ და ამერიკულ ისტორიასა და კულტურას, გარშემორტყმული ვაშინგტონის მონუმენტით და ლინკოლნის მემორიალით. ამიტომ, საქართველოს 'პერიფერიული ცივილიზაცია' ევროპისა და აზიის გზაჯვარედინზე ჩემთვის წარმოუდგენლად მომხიბლავია. მართლმადიდებლური ტრადიციები, უნიკალური ქართველური ენა და საბჭოთა ეპოქის კვალი — ყველაფერი ეს ახალი და ჯადოსნურია. მას აქვს მსგავსება ქრისტიანულ კულტურასთან, რომელიც ევროპაში ვნახე, და აღმოსავლურ კულტურასთან, რომელიც აზიაში ვნახე, თუმცა აქვს თავისი სრულიად განსხვავებული მახასიათებლები. მონუმენტის მონახულების შემდეგ, წავედი სალაშქროდ შავი ზღვის სანაპიროზე, სადაც იდეალურად ერწყმის ისტორია და ბუნება. ზუსტად ასეთი მოგზაურობა მინდა — თავისუფალი, ავთენტური, რომელიც მთავაზობს განსხვავებულ გამოცდილებას და მაძლევს საშუალებას დავაფასო სხვადასხვა კულტურის ხიბლი. სწორედ ამიტომ ვაგრძელებ მსოფლიოში მოგზაურობას."
        ]
      },
      {
        "id": "lina",
        "title": "ნაცნობი, მაგრამ უცხო კულტურული ექოს პოვნა კავკასიაში",
        "author": "@ლინა",
        "excerpt": "მე იტალიიდან ვარ, გავიზარდე ეკლესიებითა და ისტორიული მონუმენტებით გარშემორტყმული. მეგონა, რომ ვერცერთი მონუმენტი ვეღარ გამაკვირვებდა, სანამ საქართველოში არ ჩამოვედი...",
        "content": [
          "მე იტალიიდან ვარ, გავიზარდე ეკლესიებითა და ისტორიული მონუმენტებით გარშემორტყმული. კოლიზეუმი რომში, ფლორენციის საკათედრო ტაძარი და წმინდა მარკოზის ბაზილიკა ვენეციაში ღრმად არის ფესვგადგმული ჩემს ცხოვრებაში. თავდაპირველად ვფიქრობდი, რომ რაც არ უნდა განსაცვიფრებელი ყოფილიყო მონუმენტი, ის დიდად არ გამაკვირვებდა, იმის გათვალისწინებით, რომ ევროპის ამდენი კლასიკური საგანძური მქონდა ნანახი. ასე იყო მანამ, სანამ საქართველოში არ ჩამოვედი და არ ვნახე საქართველოს მატიანე. ამ მონუმენტმა, რომელიც კავკასიონის მთების მთისწინეთში მდებარეობს, მთლიანად დაამსხვრია ჩემი წინასწარ შექმნილი წარმოდგენები 'ისტორიულ ადგილებზე'.",
          "როდესაც პირველად ვნახე ეს მონუმენტი, ვიგრძენი ძლიერი ნაცნობობის გრძნობა. ბიბლიური ისტორიები ქვედა რელიეფებზე — ნოეს კიდობანი, საიდუმლო სერობა — თითქმის იდენტურად გამოიყურება ჩვენი იტალიური ეკლესიების ფრესკებისა და ქანდაკებების. მართლმადიდებლური და კათოლიკური კულტურების საერთო წარმოშობის ამ განცდამ მყისიერად ჰპოვა რეზონანსი ჩემში. მე მიმოგზაურია ევროპის ბევრ ქვეყანაში: ფრანგული ეკლესიები დახვეწილად მორთულია, გერმანული ეკლესიები საზეიმო და დიდებულია. მაგრამ ეს ქართული მონუმენტი იდეალურად აერთიანებს რელიგიურ კულტურას ადგილობრივ ისტორიასთან. ის ატარებს ევროპული რელიგიური კულტურის ჩრდილს, ამავდროულად აჩვენებს კავკასიის რეგიონალურ მახასიათებლებს. მე ვერ შევიკავე თავი, რომ არ გავჩერებულიყავი და სათითაოდ არ გამეშიფრა დეტალები რელიეფებზე, თითქოს ვუყურებდი ნაცნობ ისტორიას შერეულს უცნაურ სიახლესთან. საბოლოო ჯამში, ეს არის ქრისტიანული ცივილიზაციის გავრცელება კავკასიაში, რომელსაც აქვს მსგავსება ჩვენს ევროპულ რელიგიურ კულტურასთან, მაგრამ გააჩნია საკუთარი უნიკალური ხიბლი. ეს რეგიონთაშორისი კულტურული რეზონანსი არის ის, რაც სხვაგან არსად განმიცდია.",
          "ჩემთვის არის კიდევ ერთი მნიშვნელოვანი მიზეზი საქართველოს მოსანახულებლად — წარმოუდგენელი ფასი და ხარისხი. მე ბევრი მიმოგზაურია ევროპაში, და დასავლეთ ევროპაში ცხოვრების მაღალი ღირებულება შეიძლება შემაკავებელი იყოს. ერთი ფინჯანი ყავა პარიზში 5 ევრო ღირს, ხოლო უბრალო კვება ლონდონში — 20 ევრო. აქ ყავა მხოლოდ 3 ევროა, ხოლო ადგილობრივი საფირმო კერძი — მხოლოდ 10 ევრო. უფრო მეტიც, პეიზაჟი ადვილად უწევს კონკურენციას ალპებს. შავი ზღვის სანაპიროს ხედები კიდევ უფრო მშვიდი და ლამაზია, ვიდრე ხმელთაშუა ზღვა. აქ არ არის მასიური ხალხმრავლობა, არ არის კომერციული ხმაური — მხოლოდ სუფთა ბუნება და სილამაზე. ჩვენთვის, ევროპელებისთვის, ეს ჰგავს 'დაბალბიუჯეტიან სამოთხეს დასვენებისთვის', სადაც შეგიძლიათ განიცადოთ განსხვავებული კულტურა დასვენებით ტკბობის პარალელურად. რატომ არ უნდა მოხვიდეთ?",
          "მე მირჩევნია ნელი მოგზაურობა. ბევრ ქვეყანაში ნამყოფს, ყოველთვის ვგრძნობ, რომ მოგზაურობის აზრი არ არის იმაში, რომ მოვნიშნოთ რაც შეიძლება მეტი ატრაქციონი, არამედ ადგილობრივი ცხოვრების შეცნობაში. მონუმენტის მონახულების შემდეგ არ მიჩქარია წასვლა. ამის ნაცვლად, წავედი თბილისის ძველ ქალაქში. ვესტუმრე გოგირდის აბანოებს; თბილი წყაროს წყალი ძალიან ჰგავს ჩვენს თერმულ აბანოებს იტალიაში, მაგრამ გოგირდის უნიკალური ელფერით. დავათვალიერე ძველმანების ბაზრობა, სადაც ხელნაკეთი ნივთები აერთიანებს ევროპულ დახვეწილობას და აღმოსავლურ რუსტიკულ ხიბლს. გავსინჯე ადგილობრივი ყველის პური (ხაჭაპური) და ღვინო; ყველის სიმდიდრეს და ღვინის სიტკბოს აქვს მსგავსება იტალიურ სამზარეულოსთან, მაგრამ ატარებს მკაფიო კავკასიურ გემოს. ძველი ქალაქის მოედანზე ჯდომისას, გამვლელებზე დაკვირვებისა და ადგილობრივი ღვინის წრუპვისას, უცებ ვიგრძენი, რომ მოგზაურობის ნამდვილი აზრი არის ნაცნობი შტრიხების პოვნა უცნობ ადგილებში, გეოგრაფიული საზღვრების გადაკვეთა და სხვადასხვა კულტურის სილამაზის გაგება.",
          "მონუმენტის სკულპტურულმა სტილმაც ძალიან დამაინტრიგა. დიზაინერმა, ზურაბ წერეთელმა, იდეალურად შეაერთა ბიზანტიური ხელოვნება, ტრადიციული ქართული რელიეფები და მოდერნიზმი. მას აქვს კლასიკური ევროპული სკულპტურის დახვეწილობა და აღმოსავლური ხელოვნების სიმძიმე. ვერ შევიკავე თავი, რომ არ ამომეღო კამერა თითოეული დეტალის დასაფიქსირებლად, ვგეგმავდი მათ გაზიარებას მეგობრებთან სამშობლოში. მინდა ვუთხრა მათ, რომ კავკასიაში არის მონუმენტი, რომელიც ინახავს ევროპული კულტურის ექოს, ასევე უნიკალურ აღმოსავლურ ხიბლს. მე მინახავს ქანდაკებები მთელ მსოფლიოში: მიქელანჯელოს დავითი იტალიაში დახვეწილად სრულყოფილია, ვენერა მილოსელი საფრანგეთში ელეგანტურად ამაღელვებელია. ამ მონუმენტის ქანდაკებები შეიძლება არ იყოს 'სრულყოფილი' კლასიკური გაგებით, მაგრამ ისინი ფლობენ უზარმაზარ ძალას. ისინი ატარებენ საქართველოს ისტორიას და ევრაზიული კულტურების შერწყმას. ეს არის მისი ყველაზე უნიკალური ხიბლი."
        ]
      },
      {
        "id": "katya",
        "title": "ნოსტალგიისა და სიმშვიდის პოვნა მონუმენტის ქვეშ",
        "author": "@კატია",
        "excerpt": "საქართველოში ჩამოსვლა ჩემთვის უფრო მეტად მიკუთვნებულობის გრძნობის ძიებაა, ვიდრე მოგზაურობა. როგორც რუსისთვის, საქართველო არასდროს ყოფილა ჩემთვის უცხო ქვეყანა...",
        "content": [
          "საქართველოში ჩამოსვლა ჩემთვის უფრო მეტად მიკუთვნებულობის გრძნობის ძიებაა, ვიდრე მოგზაურობა. როგორც რუსს, ბევრ ქვეყანაში მიმოგზაურია: ვყოფილვარ პეკინსა და შანხაიში ჩინეთში, შევიგრძენი აღმოსავლური კულტურის ხიბლი; ვყოფილვარ პარიზსა და ბერლინში ევროპაში, ვიგრძენი დასავლური კულტურის რომანტიკა; და ვესტუმრე ბანგკოკსა და კუალა-ლუმპურს სამხრეთ-აღმოსავლეთ აზიაში, დავტკბი ცოცხალი ტროპიკული ატმოსფეროთი. თუმცა, საქართველო არასდროს ყოფილა ჩემთვის უცხო ქვეყანა. კულტურა, რწმენა და საჭმელიც კი აქ ძალიან ბევრ მსგავსებას იზიარებს ჩვენსასთან. საქართველოს მატიანე, კერძოდ, დამეხმარა დიდი ხნის წინ დაკარგული ნაცნობობის გრძნობის პოვნაში — გრძნობა, რომელსაც სხვა ვერცერთ ქვეყანაში ვერ ვპოულობდი.",
          "ფრენას მოსკოვიდან თბილისში მხოლოდ 2 საათი სჭირდება. ფრენები იაფია და უვიზოა. ჩემთვის ეს ჰგავს მოკლე გაქცევას. ბოლოდროინდელი კონფლიქტების შემდეგ, მუდმივად დაღლილობას ვგრძნობდი, ყოველთვის მინდოდა მეპოვა წყნარი ადგილი დასასვენებლად და ხმაურისა და დავებისგან თავის დასაღწევად. ბევრ ქვეყანაში ვყოფილვარ, მაგრამ არცერთს არ მოუცია სიმშვიდის ასეთი განცდა, სანამ საქართველოში არ ჩამოვედი. აქ არ არის ომის ჩრდილი, არ არის ხმაურიანი ხალხმრავლობა — მხოლოდ სიმშვიდე და სილამაზეა. ეს ზუსტად რუსულ სოფელს ჰგავს, თბილსა და სამკურნალოს, მაგრამ ევრაზიული გზაჯვარედინის უნიკალური ელფერით.",
          "როდესაც მონუმენტის წინ ვიდექი, ნაცნობ მართლმადიდებლურ ხატებსა და საბჭოთა ეპოქის არქიტექტურულ სტილს ვუყურებდი, თვალები უცებ ცრემლებით ამევსო. ეს მონუმენტი აშენდა საბჭოთა ეპოქაში; ეს არის ჩვენი საერთო ისტორიული მეხსიერება. ყოველი მასიური ბრინჯაოს სვეტი ატარებს ჩემს მოგონებებს წარსულზე და მეგობრობაზე ჩვენს ორ ერს შორის. ისევე როგორც წითელი მოედანი ან წმინდა ბასილის ტაძარი მოსკოვში, ეს არის შეუცვლელი კულტურული სიმბოლო ჩვენს გულებში. რელიეფების ფაქტურებზე შეხებისას, ვგრძნობდი, თითქოს შემეძლო დამეჭირა იმდროინდელი მშენებლების განზრახვები. ეს კულტურული სიახლოვე შეუცვლელია. მე ვესტუმრე ისტორიულ ადგილებს ბევრ ქვეყანაში — ჩინეთის დიდი კედელი დიდებულია, ეიფელის კოშკი საფრანგეთში რომანტიულია — მაგრამ არცერთ მათგანს არ მოუცია მიკუთვნებულობის ისეთი ძლიერი გრძნობა, როგორც ამ მონუმენტმა.",
          "სხვა ტურისტებისგან განსხვავებით, არ მიჩქარია ფოტოების გადაღება. ამის ნაცვლად, ვიპოვე წყნარი კუთხე, დავჯექი ბალახზე, გავხედე შორეულ თბილისის ზღვას, ვიგრძენი ნიავი და უბრალოდ დავაცარიელე გონება. აქ არ არის ხმაური, არ არის კონფლიქტი, მხოლოდ მშვიდობა და სილამაზეა, რაც მაძლევს საშუალებას დროებით დავივიწყო ყველა ჩემი საზრუნავი. ზოგჯერ ვესაუბრები ადგილობრივ რუს იმიგრანტებს და ვუსმენ მათ ისტორიებს აქ ცხოვრების შესახებ. ემიგრანტების ეს რეზონანსი ძალიან მათბობს. მე ასევე ვურთიერთობ ადგილობრივ ქართველებთან; ისინი არიან ვნებიანები და კეთილები. ისევე როგორც ჩვენ რუსებს, მათაც აქვთ ცხოვრების ღრმა სიყვარული და პატივისცემა ისტორიისადმი. ეს ტრანსნაციონალური მეგობრობა ღრმად მაღელვებს.",
          "ჩემთვის ეს მონუმენტი არ არის მხოლოდ ისტორიული ადგილი; ეს არის სულიერი თავშესაფარი. ის იყო საქართველოს ისტორიისა და ჩვენი ორი ქვეყნის საერთო წარსულის მოწმე. აქ შემიძლია ვიპოვო ჩემი კულტურული ფესვები და შინაგანი სიმშვიდე. ყოველ ჯერზე, როცა ვსტუმრობ, ვგრძნობ სიმყარეს, თითქოს მთელი ჩემი ნოსტალგია შეიძლება უსაფრთხოდ დაისვენოს აქ. მე მიმოგზაურია ბევრ ადგილას და მინახავს ბევრი პეიზაჟი, მაგრამ მე უნიკალურად ვანიჭებ უპირატესობას ამ ადგილს. მე ვანიჭებ უპირატესობას ამ რეგიონთაშორის სიახლოვეს და ამ მშვიდობასა და სილამაზეს. თუ ოდესმე ჩამოხვალთ საქართველოში, აუცილებლად უნდა ეწვიოთ ამ მონუმენტს. ის დაგეხმარებათ გაიგოთ რა არის კულტურული რეზონანსი, რა არის შინაგანი სიმშვიდე და მიგახვედრებთ, რომ არ აქვს მნიშვნელობა სად ხართ, კულტურის ძალას ყოველთვის შეუძლია გადაკვეთოს გეოგრაფიული საზღვრები და გაათბოს ადამიანების გულები."
        ]
      }
    ]
  }
};

const locales = ['zh-hans', 'zh-hant', 'en', 'ru', 'ka'];

locales.forEach(locale => {
  const filePath = path.join(__dirname, `../../messages/${locale}.json`);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  
  data.blogs = blogs[locale];
  
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
});

console.log('Successfully updated JSON files.');
